;;; config.el -*- lexical-binding: t; -*-

;;
;;; Fonts
;;
;; - Doom ships Fira Code at 12pt; both changed here because 12 was small.
;; - CaskaydiaCove Nerd Font is already installed system-wide
;;   (nerd-fonts.caskaydia-cove in hosts/nixos/modules/fonts.nix), so no font
;;   work needed — and the Nerd glyphs keep dashboard/neotree icons rendering.
;; - `doom-big-font-size` is a *ratio*, not a point size (1.33 => 1.33x base).
;;   `doom-small-font-size` is relative to the default face height, so 11 stays
;;   below the 18pt base and remains readable.
(setq doom-font (font-spec :family "CaskaydiaCove Nerd Font" :size 18)
      doom-variable-pitch-font (font-spec :family "Rubik" :size 19)
      doom-big-font-size 1.33
      doom-big-font-line-height 1.1
      doom-small-font-size 11)


;;
;;; Theme
;;
;; - Primary theme is `noctalia', generated by Noctalia's emacs template
;;   (assets/noctalia/settings.toml -> [theme.templates] builtin_ids = ["emacs"]).
;;   It writes ~/.config/doom/themes/noctalia-theme.el whenever your Noctalia
;;   palette changes, so Emacs matches the rest of the desktop.
;;
;; - `custom-theme-load-path' must include that directory, otherwise `load-theme'
;;   cannot find the file: load-theme searches for `<name>-theme.el'.
;;
;; - The file is produced at RUNTIME by Noctalia, so on a fresh boot it may not
;;   exist yet. Fall back to gruvbox until it does, so startup never errors.
;;
;; - Setting `doom-theme` rather than calling `load-theme` directly keeps Doom's
;;   own hooks (org-modern integration, solaire-mode in popups).
(defconst +noctalia-themes-dir
  (expand-file-name "doom/themes"
                    (or (getenv "XDG_CONFIG_HOME")
                        (concat (getenv "HOME") "/.config"))))

(add-to-list 'custom-theme-load-path +noctalia-themes-dir)

(if (file-exists-p (expand-file-name "noctalia-theme.el" +noctalia-themes-dir))
    (setq doom-theme 'noctalia)
  ;; - 'gruvbox is the ONLY theme greduan/gruvbox-theme provides; there is no
  ;;   gruvbox-dark/gruvbox-light theme symbol. `load-theme' with NO-ENABLE
  ;;   silently no-ops on an unknown name, which is why a bad name shows up as
  ;;   "0 theme reloaded" rather than an error.
  (setq doom-theme 'gruvbox))

;; - Reload after a Noctalia palette change:
;;     M-x doom/reload-theme
;;   Noctalia's own post_hook does this automatically, but only when Emacs runs
;;   as a daemon (`emacs --daemon`), because it calls `emacsclient -e'.
(defun my-reload-noctalia-theme ()
  "Reload the Noctalia theme, if its file has appeared."
  (interactive)
  (let ((file (expand-file-name "noctalia-theme.el" +noctalia-themes-dir)))
    (if (file-exists-p file)
        (progn (load file nil t) (load-theme 'noctalia t) "Noctalia theme reloaded")
      (message "Noctalia theme not generated yet: %s" file))))

;; - Fallback themes, all preinstalled by home/modules/doom-emacs.nix, so
;;   switching needs no rebuild:
;;     M-x doom/reload-theme   after setting doom-theme
;;   gruvbox, catppuccin-dark/-light/-mocha/-macchiato,
;;   tokyonight-night/-day/-moon/-storm, dracula, nordic, nord, zenburn,
;;   material, foggy-night, base16-<scheme>



;;
;;; LSP
;;
;; - lsp-mode execs servers by bare name and resolves them with `executable-find',
;;   so the servers home/modules/doom-emacs.nix puts on PATH are found with no
;;   per-language wiring. Verified against the pinned lsp-mode 20260716.755:
;;   lsp-svelte uses `:system "svelteserver"', lsp-yaml uses
;;   `lsp-yaml-server-command' ("yaml-language-server" "--stdio"), and
;;   lsp-csharp--language-server-path already does (executable-find "OmniSharp")
;;   capitalised, matching nixpkgs. All three used to be overridden by hand here.
;;
;; - An earlier version of this file set `lsp-command-line-functions'. That
;;   variable does not exist in this lsp-mode, so the whole block — including
;;   the OmniSharp casing fix and a jdtls `-data' override — was dead code
;;   that only defined an unused global. The jdtls override was also actively
;;   wrong: pinning every Java workspace to one data dir would have had them
;;   trampling each other's indexes.
;;
;; - Known gap: this lsp-mode ships NO Java client (clients/ has 141 entries,
;;   none for jdtls), so `:lang java +lsp' gets highlighting but no server.
;;   jdt-language-server stays in extraBinPackages because that may change.

;; - Only the three options below exist in this lsp-mode and are worth setting.
;;   lsp-ensure-ignored-invisibles and lsp-auto-install-servers were also set
;;   here once; neither exists in 20260716.755, so they were no-ops. Servers
;;   come from Nix, and the download prompt is lsp-enable-suggest-server-download,
;;   which is left at its default.
(setq lsp-idle-delay 0.2
      lsp-log-io nil
      lsp-server-install-dir (concat (or (getenv "XDG_DATA_HOME")
                                          (concat (getenv "HOME") "/.local/share"))
                                      "/lsp"))

;; - Heavy per-session allocation. Doom's gcmh handles the GC strategy, so
;;   leave read-process-output-max where the lsp module put it.


;;
;;; Diagnostics (flymake) — IDE-style inline reporting
;;
;; - Doom sets `flymake-fringe-indicator-position' to `right-fringe', which puts
;;   the glyph on the far side of the window, away from the line numbers. Left
;;   fringe sits directly beside them.
(setq flymake-fringe-indicator-position 'left-fringe)

;; - Show the diagnostic text at the end of the offending line, the way an IDE
;;   prints the error next to the code. `short' = only the most severe entry per
;;   line; t would print every warning on that line, which gets noisy.
;;   Needs horizontal room — the text is truncated when the line is short.
(setq flymake-show-diagnostics-at-end-of-line 'short)

;; - Glyph shapes are flymake's defaults (a red !! for errors, a yellow ! for
;;   warnings) on compilation-error/compilation-warning. Left explicit because
;;   the left fringe is narrow and these read better than the alternatives.
(setq flymake-error-bitmap '(flymake-double-exclamation-mark compilation-error)
      flymake-warning-bitmap '(exclamation-mark compilation-warning)
      flymake-note-bitmap '(info-mark compilation-info))


;;
;;; Hover
;;
;; - Doom's `+lsp` already hooks up lsp-ui, so `lsp-ui-doc' is installed and
;;   active. Deliberately NOT setting `lsp-ui-doc-show-with-cursor': upstream
;;   defaults it to nil and turning it on makes the popup appear every time the
;;   cursor settles on a symbol. Hover stays keypress-only.
;;
;; - `lsp-ui-doc-position' and `lsp-ui-doc-delay' are left at Doom's values: it
;;   already sets position to 'at-point, and the delay only gates the
;;   auto-popup we just turned off.
(setq lsp-ui-doc-max-width 90)

;; `M-.` is the Emacs convention for "describe the thing at point", and is
;; unbound in Doom. LSP buffers only.
(with-eval-after-load 'lsp-ui
  (add-hook 'lsp-managed-mode-hook
            (lambda ()
              (local-set-key (kbd "M-.") #'lsp-ui-doc-show))))

;; `SPC c k` shows the same popup. Doom stores <leader> bindings as key
;; SEQUENCES in its own `doom-leader-map' — `(doom--define-leader-key)' does
;; (define-key doom-leader-map (kbd "c k") CMD) — not as a nested prefix map on
;; evil-leader-map, which is why walking that map finds nothing. evil-leader-map
;; is not even bound when config.el runs.
;;
;; No hook needed: +keybinds.el defvars doom-leader-map during the :doom module,
;; well before config.el is evaluated.
(define-key doom-leader-map (kbd "c k") #'lsp-ui-doc-show)


(defun my-doom-config ()
  "Set up the Nix-managed Doom profile."
  (setq-default tab-width 2
                indent-tabs-mode nil)
  ;; - evil-auto-indent fights Doom's own indentation logic; leave it off.
  (setq-default evil-auto-indent nil))

;; - Bar cursor: thin, sits at the character rather than boxing it, and reads
;;   closer to what a vim user expects. Either shape lives in the text area, so
;;   neither collides with flymake's glyph, which is drawn in the left fringe.
(setq-default cursor-type 'bar)

;; - Lint listing: Doom binds `SPC c x' to +default/diagnostics, which opens
;;   flymake's diagnostics buffer for the current file. Nothing to configure —
;;   an earlier version of this file set three variables here
;;   (flymake-suppress-diagnostics-when-logging,
;;   flymake-diagnostic-explanation-filter-predicates,
;;   flymake-indicate-diagnostics-faces) but none of them exist in Emacs 30.2,
;;   so they were no-ops that just defined unused globals.


;;
;;; Open in external app
;;
;; - Doom already binds `SPC o b` to `browse-url-of-file`, and xdg-open plus
;;   xdg-desktop-portal are both live on this system, so a file at point
;;   already opens in its desktop app (PDF -> zathura, image -> eog, ...).
;;   These add file-at-point and URL-at-point without the lookup machinery.
(global-set-key (kbd "C-c C-o") #'browse-url-file-url)
(global-set-key (kbd "C-c C-r") #'browse-url-at-point)

(defun my-browse-region ()
  "Open the region under point as a URL, or the whole buffer if unmarked."
  (interactive)
  (browse-url (if (use-region-p)
                  (buffer-substring-no-properties (region-beginning) (region-end))
                (thing-at-point 'url-or-file 'no-properties))))
(global-set-key (kbd "C-c C-a") #'my-browse-region)



;;
;;; Dired
;;
;; - +icons needs a nerd font in the dired buffer; already installed.

(setq dired-listing-format
      ;; - must be ONE value: wrap the per-column entries in `list'. Writing
      ;;   `(cons ...)' and the alist as two separate arguments is a 3-argument
      ;;   setq, which throws wrong-number-of-arguments and aborts the rest of
      ;;   config.el at startup.
      (list (cons 'dired-extension "[%X%y %m %d %H:%M:%S]\n")
            '((dired-permits "%M %m %u %g  %d\n")
              (dired-size     "%10s\n")
              (dired-date     "%d %H:%M:%S\n"))))

(setq dired-listing-delete-markup t
      dired-use-listing-filters nil
      dired-filter-hidden-files nil
      dired-confirm-delete nil)


;;
;;; Neotree
;;
;; - git-aware sidebar (ranger-like), rather than treemacs.

(setq neo-tree-auto-indent t
      neo-tree-indentation-level 2
      neo-tree-dirname-separator "/"
      neo-tree-show-file-types nil)


;;
;;; Org
;;
;; - Treesitter-first: org-modern is installed via :lang org +pretty.

(setq org-startup-with-inline-tasks t
      org-directory "~/org/"
      org-default-notes-file "~/org/notes.org"
      org-roam-directory "~/org/roam/"
      org-log-into-drawer t
      org-adapt-indentation nil
      org-src-block-preserve-indentation nil
      org-cycle-close-headers-state-sublevels nil)


;;
;;; DAP / Dape
;;
;; - `:tools debugger` gives dape, which already ships configs for Rust, C, C++,
;;   Python, Go, JS, shell and more — `SPC d d` lists whichever ones match the
;;   current major-mode AND whose command is on $PATH.
;;
;; - Rust needs no adapter download: the lldb configs use `dape-ensure-command'
;;   (a plain executable-find on "lldb-dap"/"lldb-vscode") and nixpkgs' lldb
;;   ships `lldb-dap' in bin/. Adding `lldb' to extraBinPackages is the whole
;;   fix — clang-tools does not provide it.
;;
;; - dape-adapter-dir points into the Nix store (Doom sets it to
;;   doom-user-dir), so anything that WOULD download — cpptools' OpenDebugAD7,
;;   bashdb, debugpy — can never work. Prefer the configs that are plain
;;   commands, which is why Rust/C work and cpptools-based ones do not.
;;
;; - `dape-command` is the config prompt's initial contents, so pick the adapter
;;   automatically instead of typing `lldb-dap` at the minibuffer every time.
;;   Reuses dape's own predicates — dape--config-mode-p and dape--config-ensure
;;   are exactly what dape--read-config uses to build its suggestions — rather
;;   than hardcoding names. Hardcoding is how you end up writing `(delve)`
;;   when the config is called `dlv`; deriving it cannot drift, and it
;;   automatically picks up configs added upstream.
(defun +dape-command-for-buffer ()
  "Return the first dape config usable from the current buffer, or nil."
  (car (seq-find (lambda (entry)
                   (let ((config (cdr entry)))
                     ;; - `modes' must be non-nil. The generic `launch` entry has
                     ;;   modes nil, which makes dape--config-mode-p match EVERY
                     ;;   buffer, and it sorts first — so requiring :modes is
                     ;;   what stops the catch-all from always winning.
                     (and (plist-get config 'modes)
                          (dape--config-mode-p config)
                          (ignore-errors (dape--config-ensure config)))))
                 dape-configs)))

;; `dape-command` is read in `dape--read-config' before history and before
;; mode-based suggestions, so setting it there is what makes the choice stick.
;; `SPC d d` then just asks which program to debug. A nil result (no config
;; matched, e.g. plain text) leaves dape's own prompt alone.
(add-hook 'dape-read-config-hook
          (lambda ()
            (when-let ((command (+dape-command-for-buffer)))
              (setq dape-command (list command)))))

;; Registering additional adapter types is the extension point if you add a
;; debugger that dape does not know about:
;; (add-to-list 'dape-configs
;;              `(my-debugger :modes (rust-ts-mode) :ensure dape-ensure-command
;;                 command "my-debug-adapter" :type "lldb-dap" :cwd dape-cwd
;;                 :request "launch" :program "target/debug/app"))


;;
;;; Spell
;;
;; - hunspell + hunspellDicts.en_US come from the flake. Deliberately NOT
;;   spell-checking prog-mode: it flags every identifier (gcmh, defcustom, ...)
;;   and is the main source of Emacs pauses on large files. Use
;;   `:checkers (spell +hunspell +everywhere)` in init.el if you want it in
;;   comments only.

(setq spell-fu-incremental-timers t
      spell-fu-execute-enqueue-executor-async t)

;; - flyspell in comments and prose, which is where it's actually useful.
(add-hook 'text-mode-hook #'flyspell-mode)
(add-hook 'markdown-mode-hook #'flyspell-mode)
(add-hook 'org-mode-hook #'flyspell-mode)
